version: "3.3"

services:
  spb-backend:
    container_name: spb-backend
    build:
      context: ./backend
    networks:
      - local-net
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
  spb-frontend:
    container_name: spb-frontend
    build:
      context: ./frontend
    networks:
      - local-net
    ports:
      - "80:80"
    depends_on:
      - spb-backend

networks:
  local-net:
    driver: bridge
