version: "3.3"

services:
  spb-backend:
    container_name: spb-backend
    image: ghcr.io/burnstopper/spb-backend:1.0
    networks:
      - local-net
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "80:8080"
  # spb-frontend:
  #   container_name: spb-frontend
  #   image: ghcr.io/burnstopper/spb-frontend
  #   networks:
  #     - local-net
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend

networks:
  local-net:
    driver: bridge
